"""create skills table

Revision ID: 9ac69da99dd0
Revises: 
Create Date: 2026-09-03 23:41:55.223800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ac69da99dd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('security_level', sa.String(length=20), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=False),
    sa.Column('security_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('install_command', sa.Text(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skills_capabilities', 'skills', ['capabilities'], unique=False, postgresql_using='gin')
    op.create_index('ix_skills_created_at_desc', 'skills', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_skills_security_level'), 'skills', ['security_level'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_index('ix_skills_tags', 'skills', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skills_tags', table_name='skills', postgresql_using='gin')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_security_level'), table_name='skills')
    op.drop_index('ix_skills_created_at_desc', table_name='skills', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('ix_skills_capabilities', table_name='skills', postgresql_using='gin')
    op.drop_table('skills')
    # ### end Alembic commands ###
